### ISSUE TITLE
Error with graphQL : unknown query with 'allInstagramContent'

### ISSUE THREAD

**Issue by ollagada** [MantasMikal/gatsby-source-instagram-all#1]
Hi.

I've tried your instagram-source and instagram-source-all 

both of them, but I met all of failure with them.

although I've installed the dependencies, but graphql doesn't show up the allInstagramContent node or instagram node none of them.

So please let me know what can I do to go further from this.

Thank you for your service!

**Comment by MantasMikal** [comment]
Hey, sorry for a late reply.
Which version of Gatsby you're using? Have you tested your instagram access token?
Take a look at this [repository](https://github.com/MantasMikal/gatsby-instagram)

**Comment by Nichtkunst** [comment]
> Hi.
> 
> I've tried your instagram-source and instagram-source-all
> 
> both of them, but I met all of failure with them.
> 
> although I've installed the dependencies, but graphql doesn't show up the allInstagramContent node or instagram node none of them.
> 
> So please let me know what can I do to go further from this.
> 
> Thank you for your service!

It takes very long on a local machine until everything is fetched from the feed. At least this turned out to be main issue in my UC. Is there possibilty to fetch a certian amount of images via the graphQL query?

**Comment by MantasMikal** [comment]
> > Hi.
> > I've tried your instagram-source and instagram-source-all
> > both of them, but I met all of failure with them.
> > although I've installed the dependencies, but graphql doesn't show up the allInstagramContent node or instagram node none of them.
> > So please let me know what can I do to go further from this.
> > Thank you for your service!
> 
> It takes very long on a local machine until everything is fetched from the feed. At least this turned out to be main issue in my UC. Is there possibilty to fetch a certian amount of images via the graphQL query?

Yes, you can add limitation inside your query:
```
query InstagramPosts {
    allInstagramContent(limit: 10) {
    ....
    }
 }
```
In terms of fetching, I will definitely need to improve fetching algorithm.
Feel free to contribute

**Comment by Nichtkunst** [comment]
@MantasMikal thanks for the fast reply.

**Comment by antoniocapelo** [comment]
@ollagada did you ever solved this?

**Comment by ollagada** [comment]
@antoniocapelo nope not yet. Actually I almost gave up to use this one.

**Comment by MantasMikal** [comment]
@ollagada, @antoniocapelo I have created an [example](https://github.com/MantasMikal/gatsby-instagram), maybe it will help.
