### ISSUE TITLE
Node Error: 15847 

### ISSUE THREAD

**Issue by davidkartuzinski** [MantasMikal/gatsby-source-instagram-all#11]
Hello,

Thank you for your plugin. It's so easy to use. 

```(node:15847) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated```

I am running Node v12.13.1 and am getting the above error.  Everything works, but I thought I should make an issue so you aware.

Thanks again.

**Comment by MantasMikal** [comment]
Hi @davidkartuzinski,
Sorry for the late response. I've completely missed that Github notification.

Thank you for letting me know. This plugin will stop working on March 31, 2020, because Instagram will deprecate its API, so I don't think there's a reason to fix this now.

**Comment by davidkartuzinski** [comment]
@MantasMikal - Thanks for your answer.  That sucks.  So basically, there will not be a way to show an instagram feed on a website?

 Thank you for telling me.

And no, haha, probably no reason to fix that error...

-DK

**Comment by MantasMikal** [comment]
@davidkartuzinski Unfortunately no. There is an [alternative plugin](https://www.gatsbyjs.org/packages/gatsby-source-instagram/) that does exactly the same thing. I'm just not sure if it gets all the media

**Comment by davidkartuzinski** [comment]
@MantasMikal Thank you very much. I appreciate your help and attention.
