### ISSUE TITLE
Access Token Link not working

### ISSUE THREAD

**Issue by ThatGuySam** [MantasMikal/gatsby-source-instagram-all#12]
The link to get the access token redirects to [this page](https://support.pixelunion.net/hc/en-us/articles/360041460554-Important-notice-Instagram-feed-removal)

On a related note: Will this library work when Instagram deprecates its old API on March 31st, 2020

**Comment by MantasMikal** [comment]
@ThatGuySam Thank you for letting me know. 
Unfortunately, this will not work anymore.
I don't think there's a workaround to fetch all media from Instagram without using their new Graph API. The only option I can think of is scraping the images - but there's already a plugin that does that https://www.gatsbyjs.org/packages/gatsby-source-instagram/
