### ISSUE TITLE
Creating a link to the post on Instagram

### ISSUE THREAD

**Issue by brettdewoody** [MantasMikal/gatsby-source-instagram-all#15]
Does the Instagram API expose the ID used in the post URL on instagram.com? Ex: post URLs on Instagram have the format of:

```
https://www.instagram.com/p/CHXs5gVLpVz
```

How do we access, or create the ID used in the post URL?

**Comment by maco222** [comment]
@MantasMikal:  created pull request to allow getting permalink for post ( #17 )

**Comment by MantasMikal** [comment]
I've updated the plugin. Thanks for adding that in @maco222
