### ISSUE TITLE
Video post return null

### ISSUE THREAD

**Issue by theikid** [MantasMikal/gatsby-source-instagram-all#21]
Hi there, I really like thisp lugin which works great with gatsby v3 and the new Gatsby Image Plugin. I do only have an issue know with video post coming from the feed, localimage return null. Would it be possible in this case to replace the image with the thumbnail generated by instagram for the video ? 

Thank you for your time !

**Comment by mcljs** [comment]
![image](https://user-images.githubusercontent.com/52798639/116110630-e18d6a00-a683-11eb-8d3e-dbedc5df7af0.png)

I also have the same problem, how can I solve it? I hope someone can help

**Comment by MantasMikal** [comment]
Hey, I suggest to check if `fluid` prop exists and skip the image if it isn't there. I am a bit swamped with work, so don't have much time to look into this. Feel free to open a PR!

**Comment by MantasMikal** [comment]
@theikid  @mcljs Video images are now being replaced with the thumbnails generated by instagram.
This is availabale in version 4.1.0
