### ISSUE TITLE
error "gatsby-source-instagram-all" threw an error while running the sourceNodes lifecycle

### ISSUE THREAD

**Issue by nachiketkumar** [MantasMikal/gatsby-source-instagram-all#31]
Hi,

I am getting the same error your [last deploy preview build](https://app.netlify.com/sites/gatsby-instagram/deploys/625483e658470a0009b0c75c) got on netlify (also deploying via netlify myself):

`error "gatsby-source-instagram-all" threw an error while running the sourceNodes lifecycle: invalid json response body at https://graph.instagram.com/me/media?fields=id,media_url,media_type,permalink,timestamp,caption,username,thumbnail_url,children%7Bid,media_url,media_type,thumbnail_url,timestamp%7D&limit=30 reason: Unexpected token S in JSON at position 0`

I have no issues with getting the instagram images showing up in my local dev environment. I added my access token to my `.env.production` file as well as inside the site settings / build & deploy / environment section.

Any idea how to resolve this? Working so smoothly in local!

**Comment by MantasMikal** [comment]
Hi @nachiketkumar,
Do you still have this issue?
The error in the demo is because of expired access token.

**Comment by nachiketkumar** [comment]
> Hi @nachiketkumar,
> Do you still have this issue?
> The error in the demo occurs because of expired access token.

Yes, unfortunately I am. I went through the steps to generate an access token for the instagram tester and it is still working for me locally. I assume if it works for me locally that the access token is not expired?

**Comment by MantasMikal** [comment]
Hmm.. I've updated the [demo](https://github.com/MantasMikal/gatsby-instagram) to use env vars. It seems to be workng fine.
Try deplying it with your access token

**Comment by nachiketkumar** [comment]
Weird— I tried another build and now it's working! No idea what the glitch was, thanks for the plugin and taking a look!

**Comment by anboron** [comment]
Hello. I'm having the same issue - the plugin is working correctly in the local environment and while creating a build, exactly the same error appears. Do you know what can be the reason?
