### ISSUE TITLE
INSTAGRAM API ERROR:  undefined

### ISSUE THREAD

**Issue by leworking** [MantasMikal/gatsby-source-instagram-all#6]
Just followed the instructions, but somehow it's not accessing Instagram. When I run `develop` I get this error
```
INSTAGRAM API ERROR:  undefined
warning The gatsby-source-instagram-all plugin has generated no Gatsby nodes. Do you need it?
```

And obviously there're no Instagram query nodes to explore

My `gatsby-config`
```
module.exports = {
  siteMetadata: {
    title: `--`,
    description: `--.`,
    author: `--`,
  },
  plugins: [
    `gatsby-plugin-styled-components`,
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `markdown`,
        path: `${__dirname}/markdown`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: `gatsby-source-instagram-all`,
      options: {
        access_token: 'got from the link you provide',
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
  ],
}
```

**Comment by leworking** [comment]
Interestingly, copy&pasting your token of your demo doesn't change the message/outcome, so it's not about the token (?)

**Comment by leworking** [comment]
Having installed your demo-repo, it throws the same error, so I assume something on the Instagram side has changed (?)
Looking forward to your exploration :)

**Comment by MantasMikal** [comment]
Hey @leworking the demo repo and the plugin itself is working on my side. 
Try to make a request in your browser:
```https://api.instagram.com/v1/users/self/media/recent/?access_token=YOUR_ACCESS_TOKEN&count=30```
It might be a problem on your end. Let me know how it goes!

**Comment by destegabry** [comment]
I have the same issue, calling `https://api.instagram.com/v1/users/self/media/recent/?access_token=YOUR_ACCESS_TOKEN&count=30` with my access token gives a good response

**Comment by MantasMikal** [comment]
@destegabry Can you update the plugin its newest version? It should display the error message correctly now. Maybe that will provide some insight on what's going on.

**Comment by destegabry** [comment]
Updating the plugin just fixed the error
